vim.keymap.set('n', '<Leader>qo', ':copen<CR>', { desc = 'Custom: Open Quickfix List' })
vim.keymap.set('n', '<Leader>qc', ':cclose<CR>', { desc = 'Custom: Close Quickfix List' })
vim.keymap.set('n', '<Leader>qn', ':cnext<CR>', { desc = 'Custom: Next Quickfix List' })
vim.keymap.set('n', '<Leader>qp', ':cprev<CR>', { desc = 'Custom: Previous Quickfix List' })
vim.keymap.set('n', '<Leader>qk', ':CloakToggle<CR>', { desc = 'Custom: Toggle Cloak' })
vim.keymap.set('v', 'J', ":m '>+1<CR>gv=gv", { desc = 'Custom: Move highlighted text down' })
vim.keymap.set('v', 'K', ":m '<-2<CR>gv=gv", { desc = 'Custom: Move highlighted text up' })
vim.keymap.set('n', 'n', 'nzzzv', { desc = 'Custom: Allow next search terms to stay in the middle' })
vim.keymap.set('n', 'N', 'Nzzzv', { desc = 'Custom: Allow previous search terms to stay in the middle' })
vim.keymap.set('x', '<Leader>p', '"_dP', { desc = 'Custom: Delete highlighted word into the void register then paste previous word' })
